apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-keyvault-secrets
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: ${KEYVAULT_NAME}
    tenantId: ${AZURE_TENANT_ID}
    objects: |
      array:
        - |
          objectName: GRAFANA-ADMIN-USER
          objectType: secret
        - |
          objectName: GRAFANA-ADMIN-PASSWORD
          objectType: secret
  secretObjects:
    - secretName: grafana-secrets
      type: Opaque
      data:
        - objectName: GRAFANA-ADMIN-USER
          key: admin-user
        - objectName: GRAFANA-ADMIN-PASSWORD
          key: admin-password
