apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: journal-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.alphacloudtest.net
      secretName: journal-api-tls
  rules:
    - host: api.alphacloudtest.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: journal-api
                port:
                  number: 80
